name: CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macOS
            arch: ARM64
            triple: aarch64-apple-darwin
          - os: Linux
            arch: X64
            triple: x86_64-unknown-linux-gnu
    runs-on: [self-hosted, prod, "${{ matrix.os }}", "${{ matrix.arch }}"]
    steps:
      - name: Install nightly toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: lukka/get-cmake@v3.27.4

      - name: Show rust version
        run: |
          cargo version
          rustup toolchain list

      - name: Check out succinctlabs/rust
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          path: rust
          fetch-depth: 0

      - name: Check out succinctlabs/sp1
        uses: actions/checkout@v3
        with:
          repository: succinctlabs/sp1
          ref: dev
          path: sp1

      - name: Build
        run: |
          cd sp1/cli
          GITHUB_ACTIONS=false SP1_BUILD_DIR=$GITHUB_WORKSPACE cargo run --bin cargo-prove -- prove build-toolchain

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: rust-toolchain-${{ matrix.triple }}
          path: sp1/cli/rust-toolchain-${{ matrix.triple }}.tar.gz
          # path: |
          #   rust/build/${{ matrix.triple }}/stage2
          #   !rust/build/${{ matrix.triple }}/stage2/lib/rustlib/src
          #   !rust/build/${{ matrix.triple }}/stage2/lib/rustlib/rustc-src
